### ISSUE TITLE
Add Open-Source Resources

### ISSUE THREAD

**Issue by chryzcode** [chryz-hub/opensource-4-everyone#1]
# Add Open-Source Resources
### This issue entails you to get open source resources and make a [pull request here](https://github.com/chryz-hub/opensource-4-everyone#resources), be it :
- a blog
- book
- docs
- repositories
- open-source internships
- website based on open-source and many more

<b> Requirements</b>
All resources must be based on open-source

If you have any question, do well to ask!

**Comment by aman-godara** [comment]
Hey @chryzcodez,
Will it be good to add this [youtube link](https://www.youtube.com/watch?v=HjgZQeMrw6c&list=PLV5CVI1eNcJgNqzNwcs4UKrlJdhfDjshf) to this repository to encourage people (especially beginners) to contribute to open source projects?

**Comment by chryzcode** [comment]
> Hey @chryzcodez,
> Will it be good to add this [youtube link](https://www.youtube.com/watch?v=HjgZQeMrw6c&list=PLV5CVI1eNcJgNqzNwcs4UKrlJdhfDjshf) to this repository to encourage people (especially beginners) to contribute to open source projects?

Ok I think that is nice but give me a minute let me make a section for that of YouTube videos. 

Thanks for wanting to contribute!

**Comment by chryzcode** [comment]
Ok, I already did that. You can go on🚀

**Comment by Evavic44** [comment]
Can I add resource repositories?

**Comment by chryzcode** [comment]
> Can I add resource repositories?

Yeah you can!

**Comment by hackEibrahim** [comment]
[https://github.com/Asabeneh/30-Days-Of-JavaScript](url)
