### ISSUE TITLE
Fixing links to be active

### ISSUE THREAD

**Issue by chryzcode** [chryz-hub/opensource-4-everyone#31]
<b> This are the [active links](https://github.com/chryz-hub/opensource-4-everyone/tree/master/chryz-hub-resources/chryz-hub-%20docs)
This are the failed and [inactive links](https://github.com/chryz-hub/opensource-4-everyone/blob/master/README.md#chryz-hub-resources)
   - Replace the inactive links with the active links.

If You have any question deo well to ask!

**Comment by iamayushdas** [comment]
Assign this to me!

**Comment by chryzcode** [comment]
> Assign this to me!

I assigned this to my self, so if anyone has a question I would be able to get notified easily. I'm not going to do it, just move ahead if you can and fix it!

**Comment by chryzcode** [comment]
It's done thanks to al who contributed to this!
