### ISSUE TITLE
Arranging into a folder and fixing links

### ISSUE THREAD

**Issue by chryzcode** [chryz-hub/opensource-4-everyone#32]
**Description**
This is all about **moving not copying** folders of pictures
- https://github.com/chryz-hub/opensource-4-everyone/tree/master/chryz-hub-resources/membvispics and
- https://github.com/chryz-hub/opensource-4-everyone/tree/master/chryz-hub-resources/pr-tut-pics
into a main folder that would be called `chryz-hub-tut-pics` , this main folder would be created by you! 

After that fix the links of the picture into this tutorials
-  `membvispics` is for this
    - https://github.com/chryz-hub/opensource-4-everyone/blob/master/chryz-hub-resources/chryz-hub-%20docs/membership-visibility.md

- While `pr-tut-pics` is for this
  - https://github.com/chryz-hub/opensource-4-everyone#simple-guide-to-making-a-pull-request-or-contribution

If you have any question please do well to ask !

**Comment by zane-schaffer** [comment]
would love to hop on this!

**Comment by chryzcode** [comment]
> would love to hop on this!

Oops, you really tried but it was meant to be in different folders. You just have to move them with their folders but you removed them from their folders mixing them together in the new folder `chryz-hub-tut-pics`  that you made.

**Comment by zane-schaffer** [comment]
> > would love to hop on this!
> 
> Oops, you really tried but it was meant to be in different folders. You just have to move them with their folders but you removed them from their folders mixing them together in the new folder `chryz-hub-tut-pics` that you made.

oops! fixed it
