### ISSUE TITLE
Can we stil make a PR contribution practice ?

### ISSUE THREAD

**Issue by ManuSquall** [chryz-hub/opensource-4-everyone#59]
**Description**

Hello i found this great repo and was trying to see how can i make a PR too but it seems like you delete the last PR delete the lines where people contributed. So is it still ok to contribute on this file?

**Screenshots**

![image](https://user-images.githubusercontent.com/29026887/124384199-a335ac00-dcbf-11eb-96ea-486e945e25f9.png)

Great initiatives by the way :-).

**Comment by chryzcode** [comment]
Hi @ManuSquall,

Thanks for raising this issue, that was actually a mistake and it has been resolved.

So, please you can go ahead to make your pull request now!

Thanks
